---

- block:
    - name: Check that the /usr/local/bin/python{{ python_version }} exists
      stat:
        path: /usr/local/bin/python{{ python_version }}
      tags: python
      register: python_result

    - name: Install prerequisites
      ansible.builtin.apt:
        name={{item}} update_cache=yes
      with_items:
        - software-properties-common

    - name: Add Python{{ python_version }} APT repository
      apt_repository:
        repo: ppa:deadsnakes/ppa

    - name: Install Python{{ python_version }}
      ansible.builtin.apt:
        name={{item}} state=present update_cache=yes
      with_items:
        - python{{ python_version }}
        - python{{ python_version }}-dev

    - name: Install pip
      ansible.builtin.apt:
        name: python3-pip

  become: true
  become_user: root